### ISSUE TITLE
SIMD support

### ISSUE THREAD

**Issue by polyfloyd** [polyfloyd/edge-detection-rs#2]
The first stage (convolution) is currently the slowest part of the algorithm. SIMD could speed this up quite a bit.

Handy: https://github.com/AdamNiederer/faster

**Comment by LaVieEstDure** [comment]
Can't disassemble and check right now but at the highest optimisation levels LLVM might be able to do its own SIMD optimisations. Might also be possible to use a generic linear algebra library (nalgebra) which does optimisations for us.
